# This is a basic workflow to help you get started with Actions

name: CI1

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "pro" branch
  push:
    branches: [ "pro" ]
  pull_request:
    branches: [ "pro" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      - name: Setup SSH
        run: sudo apt install openssh-client -y
      - run: sudo apt install openssh-server -y
      - run: |
        sudo cp /etc/ssh/sshd_config /etc/ssh/sshd_config.original
        sudo chmod a-w /etc/ssh/sshd_config.original  
        sudo sshd -t -f /etc/ssh/sshd_config


      - name: Setup  NGROK
        run:  wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-darwin-amd64.zip ~/downloads/ngrok-v3-stable-darwin-amd64.zip
      - run: sudo unzip ~/Downloads/ngrok-v3-stable-darwin-amd64.zip -d /usr/local/bin
      - run: ngrok config add-authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

      - run: ngrok tcp 22
      
